### PR TITLE
Add CakePHP CodeSniffer

### PR DESCRIPTION
**Pull request by ravage84**
Also added Composer commands for executing PHPCS & PHPUnit

And improve code style.

### CODE REVIEW

**Comment by mentisy** [comment]
Genuine question, shouldn't the cakephp-codesniffer be inside require-dev and not require, as it's not pertinent to regular everyday use.

https://github.com/orca-services/cakephp-heartbeat/blob/058b31605cb9de60a1c933df47fe1081de6153c3/composer.json#L36-L39

**Comment by ravage84** [comment]
> Genuine question, shouldn't the cakephp-codesniffer be inside require-dev and not require, as it's not pertinent to regular everyday use.

Yes, it should. I often forget to add ``--dev`` when I require stuff with Composer.
Thank you for pointing that out.

**Comment by mentisy** [comment]
> > Genuine question, shouldn't the cakephp-codesniffer be inside require-dev and not require, as it's not pertinent to regular everyday use.
> 
> Yes, it should. I often forget to add `--dev` when I require stuff with Composer.
> Thank you for pointing that out.

You and me both!

**Comment by ravage84** [comment]
@mentisy  fixed

**Pull request merged**
